# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Defaults Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛


# General
$filemanager = thunar
$applauncher = wofi --show drun
$terminal = warp-terminal
$idlehandler = hypridle

# Screenshots
$shot-region = flameshot gui
$shot-window = grimblast copy active
$shot-screen = grimblast copy output
