# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                      Input Configuration                    ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# Input wiki https://wiki.hyprland.org/Configuring/Variables/#input

input {
    kb_layout = es
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 2 # 0|1|2|3
    float_switch_override_focus = 2

    repeat_rate = 25
    repeat_delay = 600

    # Allow special Fn key combinations to pass through (for ASUS ROG)
    resolve_binds_by_sym = false

    touchpad {
        natural_scroll = true
        disable_while_typing = true
        tap-to-click = true
    }

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}
