# Disable Logitech BRIO IR/greyscale node that appears as a duplicate camera
# and can be selected by WebRTC apps when enabling background effects.
monitor.v4l2.rules = [
  {
    matches = [
      {
        device.api = "v4l2"
        api.v4l2.path = "/dev/video2"
      }
    ]
    actions = {
      update-props = {
        node.disabled = true
      }
    }
  }
]
